### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by 2bitninja** [2bitninja/mass_rename#2]
Need to test script on different Operating systems.

- [ ] #6
- [x] #7
- [x] #8
- [x] #9
- [x] Debian / ubuntu / etc...
- [ ] #10

If anyone knows of operating system I'm missing let me know and I will add it.

**Comment by ivan-developer-01** [comment]
Maybe I can test on Linux Mint?

**Comment by 2bitninja** [comment]
Sure that would be great.
 I'm sill pretty new to Github, so I don't know everything yet. I think I could create anther issue if you want to to be shown as helping. I'm not sure. I see you have a nice readme on your GitHub. Just let me know what to do.

**Comment by 2bitninja** [comment]
@ivan-developer-01 I added an issue for you to do testing. I'm not sure I did it right, I'm still learning.

**Comment by ivan-developer-01** [comment]
@2bitninja Yes, you did it right.
